---
kind: pipeline
name: docker-images

platform:
  os: linux
  arch: amd64

steps:
  - name: buildimg
    image: ayravat/debian:10-docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: dockerhome
        path: /root/.docker
    commands:
      - sh build.sh
    branch:
      - master
    event:
      - push

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: dockerhome
    host:
      path: /root/.docker
...
