---
kind: pipeline
name: docker-images

platform:
  os: linux
  arch: amd64

steps:
  - name: buildimg
    image: ayravat/debian:10-docker
    volumes:
      - name: dockersock
        path: /var/run/docker.sock
      - name: dockerhome
        path: /root/.docker
    commands:
      - sh build.sh
    when:
      branch:
        - master
      event:
        - push

  - name: notify
    image: drillster/drone-email
    environment:
      PLUGIN_HOST:
        from_secret: mail_host
      PLUGIN_FROM:
        from_secret: mail_sender
      PLUGIN_FROM_NAME:
        from_secret: mail_sender_name
      PLUGIN_PORT:
        from_secret: mail_port
      PLUGIN_USERNAME:
        from_secret: mail_user
      PLUGIN_PASSWORD:
        from_secret: mail_password
      PLUGIN_RECIPIENTS:
        from_secret: mail_recipients
    when:
      status:
        - failure

volumes:
  - name: dockersock
    host:
      path: /var/run/docker.sock
  - name: dockerhome
    host:
      path: /root/.docker
...
